// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniLibrary.DataAccess.Data;

#nullable disable

namespace MiniLibrary.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260730233208_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("AuthorBook");

                    b.HasData(
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 1
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 2
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 3
                        },
                        new
                        {
                            AuthorsId = 4,
                            BooksId = 4
                        },
                        new
                        {
                            AuthorsId = 5,
                            BooksId = 5
                        },
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 6
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 7
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 8
                        });
                });

            modelBuilder.Entity("MiniLibrary.Models.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "John Doe is a prolific author known for his thrilling novels.",
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Jane Smith is a renowned author who has written numerous bestsellers in the romance genre.",
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Michael Johnson is an award-winning author specializing in historical fiction.",
                            FirstName = "Michael",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Emily Davis is a talented author known for her captivating fantasy novels.",
                            FirstName = "Emily",
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "David Wilson is a versatile author who has written across various genres, including mystery and thriller.",
                            FirstName = "David",
                            LastName = "Wilson"
                        });
                });

            modelBuilder.Entity("MiniLibrary.Models.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ISBN = "1234567890",
                            Price = 9.99m,
                            PublisherId = 1,
                            Title = "Book 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            ISBN = "0987654321",
                            Price = 14.99m,
                            PublisherId = 1,
                            Title = "Book 2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            ISBN = "5678901234",
                            Price = 19.99m,
                            PublisherId = 2,
                            Title = "Book 3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ISBN = "9876543210",
                            Price = 24.99m,
                            PublisherId = 3,
                            Title = "Book 4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ISBN = "4321098765",
                            Price = 29.99m,
                            PublisherId = 3,
                            Title = "Book 5"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            ISBN = "2468135790",
                            Price = 12.99m,
                            PublisherId = 2,
                            Title = "Book 6"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            ISBN = "1357924680",
                            Price = 17.99m,
                            PublisherId = 1,
                            Title = "Book 7"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            ISBN = "8642097531",
                            Price = 22.99m,
                            PublisherId = 3,
                            Title = "Book 8"
                        });
                });

            modelBuilder.Entity("MiniLibrary.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Science"
                        });
                });

            modelBuilder.Entity("MiniLibrary.Models.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            Name = "Publisher 1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ave",
                            Name = "Publisher 2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine Rd",
                            Name = "Publisher 3"
                        });
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("MiniLibrary.Models.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniLibrary.Models.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniLibrary.Models.Models.Book", b =>
                {
                    b.HasOne("MiniLibrary.Models.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniLibrary.Models.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("MiniLibrary.Models.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("MiniLibrary.Models.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
